"""
idioms_dict.py — Textos fijos de la interfaz (no las respuestas del agente,
esas ya vienen en el idioma que el propio agente decida usar).

Añadir un idioma nuevo: copiar un bloque, traducir los valores, y
añadir la entrada correspondiente en LANGUAGES.
"""

LANGUAGES = {
    "es": {"label": "Español", "flag": "🇪🇸"},
    "en": {"label": "English", "flag": "🇬🇧"},
    "fr": {"label": "Français", "flag": "🇫🇷"},
    "de": {"label": "Deutsch", "flag": "🇩🇪"},
    "it": {"label": "Italiano", "flag": "🇮🇹"},
    "pt": {"label": "Português", "flag": "🇵🇹"},
    "pt-BR": {"label": "Português (Brasil)", "flag": "🇧🇷"},
}

TEXT = {
    "es": {
        "app_title": "EMT Madrid — Pregúntame por tu bus",
        "app_subtitle": "Pregunta cuándo llega tu autobús en el centro de Madrid",
        "chat_placeholder": "Ej: ¿Cuándo llega el M1 a Sol?",
        "send_message": "Enviar",
        "voice_button_help": "Probar micrófono",
        "voice_transcribed": "Voz transcrita en el cuadro de texto.",
        "voice_error": "No se pudo transcribir la voz. Comprueba el micrófono y las claves de Azure Speech.",
        "thinking": "Buscando tu autobús...",
        "welcome": "¡Hola! Pregúntame cuándo llega tu autobús, o qué líneas pasan por una parada del centro de Madrid.",
        "feedback_prompt": "¿Te ha servido esta respuesta?",
        "feedback_thanks": "¡Gracias por tu ayuda!",
        "sidebar_title": "Ajustes",
        "sidebar_language": "Idioma",
        "sidebar_theme": "Modo de color",
        "theme_dark": "Oscuro",
        "theme_colorblind": "Alto contraste (daltónico)",
        "sidebar_text_size": "Tamaño del texto",
        "text_size_normal": "Normal",
        "text_size_large": "Grande",
        "backend_badge_mock": "Modo demo (datos de prueba)",
        "backend_badge_local": "Conectado al agente local",
        "backend_badge_azure": "Conectado en vivo",
        "clear_chat": "Empezar de nuevo",
        "footer": "Proyecto final Factoría F5 × Microsoft — EMT Madrid",
    },
    "en": {
        "app_title": "EMT Madrid — Ask about your bus",
        "app_subtitle": "Ask when your bus arrives in the center of Madrid",
        "chat_placeholder": "E.g: When does the M1 arrive at Sol?",
        "send_message": "Send",
        "voice_button_help": "Test microphone",
        "voice_transcribed": "Voice transcribed into the text box.",
        "voice_error": "Voice could not be transcribed. Check the microphone and Azure Speech credentials.",
        "thinking": "Looking up your bus...",
        "welcome": "Hi! Ask me when your bus is arriving, or which lines stop at a given stop in central Madrid.",
        "feedback_prompt": "Was this answer helpful?",
        "feedback_thanks": "Thanks for the feedback!",
        "sidebar_title": "Settings",
        "sidebar_language": "Language",
        "sidebar_theme": "Color mode",
        "theme_dark": "Dark",
        "theme_colorblind": "High contrast (colorblind)",
        "sidebar_text_size": "Text size",
        "text_size_normal": "Normal",
        "text_size_large": "Large",
        "backend_badge_mock": "Demo mode (sample data)",
        "backend_badge_local": "Connected to local agent",
        "backend_badge_azure": "Live connection",
        "clear_chat": "Start over",
        "footer": "Factoría F5 × Microsoft final project — EMT Madrid",
    },
    "fr": {
        "app_title": "EMT Madrid — Renseignez-vous sur votre bus",
        "app_subtitle": "Demandez à quelle heure votre bus arrive au centre de Madrid",
        "chat_placeholder": "Ex: Quand arrive le M1 à Sol ?",
        "send_message": "Envoyer",
        "voice_button_help": "Tester le microphone",
        "voice_transcribed": "Voix transcrite dans la zone de texte.",
        "voice_error": "La voix n'a pas pu être transcrite. Vérifiez le microphone et les identifiants Azure Speech.",
        "thinking": "Recherche de votre bus...",
        "welcome": "Bonjour ! Demandez-moi quand votre bus arrive, ou quelles lignes desservent un arrêt du centre de Madrid.",
        "feedback_prompt": "Cette réponse vous a-t-elle été utile ?",
        "feedback_thanks": "Merci pour votre retour !",
        "sidebar_title": "Paramètres",
        "sidebar_language": "Langue",
        "sidebar_theme": "Mode couleur",
        "theme_dark": "Sombre",
        "theme_colorblind": "Contraste élevé (daltonien)",
        "sidebar_text_size": "Taille du texte",
        "text_size_normal": "Normal",
        "text_size_large": "Grand",
        "backend_badge_mock": "Mode démo (données d'exemple)",
        "backend_badge_local": "Connecté à l'agent local",
        "backend_badge_azure": "Connexion en direct",
        "clear_chat": "Recommencer",
        "footer": "Projet final Factoría F5 × Microsoft — EMT Madrid",
    },
    "de": {
        "app_title": "EMT Madrid — Frag nach deinem Bus",
        "app_subtitle": "Frag, wann dein Bus im Zentrum Madrids ankommt",
        "chat_placeholder": "Z.B: Wann kommt der M1 in Sol an?",
        "send_message": "Senden",
        "voice_button_help": "Mikrofon testen",
        "voice_transcribed": "Sprache in das Textfeld transkribiert.",
        "voice_error": "Die Sprache konnte nicht transkribiert werden. Prüfen Sie das Mikrofon und die Azure-Speech-Anmeldeinformationen.",
        "thinking": "Suche deinen Bus...",
        "welcome": "Hallo! Frag mich, wann dein Bus ankommt, oder welche Linien an einer Haltestelle im Zentrum halten.",
        "feedback_prompt": "War diese Antwort hilfreich?",
        "feedback_thanks": "Danke für dein Feedback!",
        "sidebar_title": "Einstellungen",
        "sidebar_language": "Sprache",
        "sidebar_theme": "Farbmodus",
        "theme_dark": "Dunkel",
        "theme_colorblind": "Hoher Kontrast (farbenblind)",
        "sidebar_text_size": "Textgröße",
        "text_size_normal": "Normal",
        "text_size_large": "Groß",
        "backend_badge_mock": "Demo-Modus (Testdaten)",
        "backend_badge_local": "Mit lokalem Agenten verbunden",
        "backend_badge_azure": "Live-Verbindung",
        "clear_chat": "Neu starten",
        "footer": "Factoría F5 × Microsoft Abschlussprojekt — EMT Madrid",
    },
    "it": {
        "app_title": "EMT Madrid — Chiedi del tuo autobus",
        "app_subtitle": "Chiedi quando arriva il tuo autobus nel centro di Madrid",
        "chat_placeholder": "Es: Quando arriva la M1 a Sol?",
        "send_message": "Invia",
        "voice_button_help": "Prova il microfono",
        "voice_transcribed": "Voce trascritta nella casella di testo.",
        "voice_error": "Impossibile trascrivere la voce. Controlla il microfono e le credenziali Azure Speech.",
        "thinking": "Cerco il tuo autobus...",
        "welcome": "Ciao! Chiedimi quando arriva il tuo autobus, o quali linee passano per una fermata del centro di Madrid.",
        "feedback_prompt": "Questa risposta ti è stata utile?",
        "feedback_thanks": "Grazie per il feedback!",
        "sidebar_title": "Impostazioni",
        "sidebar_language": "Lingua",
        "sidebar_theme": "Modalità colore",
        "theme_dark": "Scuro",
        "theme_colorblind": "Alto contrasto (daltonico)",
        "sidebar_text_size": "Dimensione testo",
        "text_size_normal": "Normale",
        "text_size_large": "Grande",
        "backend_badge_mock": "Modalità demo (dati di prova)",
        "backend_badge_local": "Connesso all'agente locale",
        "backend_badge_azure": "Connessione live",
        "clear_chat": "Ricomincia",
        "footer": "Progetto finale Factoría F5 × Microsoft — EMT Madrid",
    },
    "pt": {
        "app_title": "EMT Madrid — Pergunte sobre o seu autocarro",
        "app_subtitle": "Pergunte quando chega o seu autocarro no centro de Madrid",
        "chat_placeholder": "Ex: Quando chega o M1 a Sol?",
        "send_message": "Enviar",
        "voice_button_help": "Testar microfone",
        "voice_transcribed": "Voz transcrita na caixa de texto.",
        "voice_error": "Não foi possível transcrever a voz. Verifique o microfone e as credenciais do Azure Speech.",
        "thinking": "A procurar o seu autocarro...",
        "welcome": "Olá! Pergunte-me quando chega o seu autocarro, ou que linhas passam numa paragem do centro de Madrid.",
        "feedback_prompt": "Esta resposta foi útil?",
        "feedback_thanks": "Obrigado pelo feedback!",
        "sidebar_title": "Definições",
        "sidebar_language": "Idioma",
        "sidebar_theme": "Modo de cor",
        "theme_dark": "Escuro",
        "theme_colorblind": "Alto contraste (daltónico)",
        "sidebar_text_size": "Tamanho do texto",
        "text_size_normal": "Normal",
        "text_size_large": "Grande",
        "backend_badge_mock": "Modo demo (dados de teste)",
        "backend_badge_local": "Ligado ao agente local",
        "backend_badge_azure": "Ligação em direto",
        "clear_chat": "Recomeçar",
        "footer": "Projeto final Factoría F5 × Microsoft — EMT Madrid",
    },
    "pt-BR": {
        "app_title": "EMT Madrid — Pergunte sobre o seu ônibus",
        "app_subtitle": "Pergunte quando o seu ônibus chega no centro de Madrid",
        "chat_placeholder": "Ex: Quando o M1 chega em Sol?",
        "send_message": "Enviar",
        "voice_button_help": "Testar microfone",
        "voice_transcribed": "Voz transcrita na caixa de texto.",
        "voice_error": "Não foi possível transcrever a voz. Verifique o microfone e as credenciais do Azure Speech.",
        "thinking": "Procurando o seu ônibus...",
        "welcome": "Olá! Pergunte-me quando o seu ônibus chega, ou quais linhas passam por uma parada no centro de Madrid.",
        "feedback_prompt": "Essa resposta foi útil?",
        "feedback_thanks": "Obrigado pelo feedback!",
        "sidebar_title": "Configurações",
        "sidebar_language": "Idioma",
        "sidebar_theme": "Modo de cor",
        "theme_dark": "Escuro",
        "theme_colorblind": "Alto contraste (daltônico)",
        "sidebar_text_size": "Tamanho do texto",
        "text_size_normal": "Normal",
        "text_size_large": "Grande",
        "backend_badge_mock": "Modo demo (dados de exemplo)",
        "backend_badge_local": "Conectado ao agente local",
        "backend_badge_azure": "Conexão ao vivo",
        "clear_chat": "Começar de novo",
        "footer": "Projeto final Factoría F5 × Microsoft — EMT Madrid",
    },
}


def t(lang: str, key: str) -> str:
    """Traducción con fallback a español si falta la clave o el idioma."""
    return TEXT.get(lang, TEXT["es"]).get(key, TEXT["es"].get(key, key))
